name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    strategy:
      matrix:
        build_type: [Debug] #, Release]
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Necessary Packages
        run: sudo apt update && sudo apt install -y cmake build-essential ninja-build

      - name: Install GCC
        if: ${{ matrix.compiler == 'gcc' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64

      - name: Install Clang
        if: ${{ matrix.compiler == 'clang' }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64

      - name: Configure CMake
        run: cmake -G "Ninja" -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        working-directory: ${{env.BUILD_DIR}}
        run: cmake --build . --config ${{matrix.build_type}} -- -j$(nproc)
